Repository smeup/ketchup, pull requests merged in 2021-06, with the labels that each got.

#1050 Bugfix: badge wasn't displayed in image cells.
  packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
  packages/ketchup/src/components/kup-data-table/modules/kup-data-table-main.scss
Labels: master

#1062 Bugfix: editable text field in cell update was testing/updating initialValue instead of value.
  packages/ketchup-showcase/package.json
  packages/ketchup/package.json
  packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
Labels: master

#1066 kup-data-table and kup-tree: global filter applied only for visible columns; column filter applied anyway
  packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
  packages/ketchup/src/components/kup-tree/kup-tree.tsx
  packages/ketchup/src/utils/filters/filters-rows.ts
Labels: kup-data-table, kup-tree

#1068 Bugfix: number cells in data table were not right-aligned when the forceOneLine prop was true.
  packages/ketchup/src/components/kup-data-table/styles/kup-data-table-main.scss
Labels: release
